version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - git checkout 3.11
    - make build SPHINXERRORHANDLING=""
    - install -dm755 _readthedocs/html
    - cp -r cpython/Doc/build/html/* _readthedocs/html
